resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/kahbenya/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
- name: wait-app
  plan:
  - get: flight-school
    trigger: true
  - task: wait
    file: flight-school/ci/build2.yml
- name: follow-up
  plan:
  - get: flight-school
    trigger: true
    passed: [test-app]
  - task: sum
    file: flight-school/ci/build3.yml

